### ISSUE TITLE
Game Entities Revamp Suggestion

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1188]
There are some ( #855, #944, #981, #1030, #1152 ) issues which can be difficult to solve in our current system of storing information about games, rom versions, and publications.
A big problem comes from the isolated design of our Game system, where e.g. Windows VVVVVV and Linux VVVVVV don't have a connection.

<hr>

<details>
<summary>Original Post 2022-03-23</summary>

After some discussions, here is my suggested solution: Redesign the Game Entities.
### Current System
Our current Game Entity is the abstract idea of a game on one platform, and this game is then split into different types of ROM versions. These can have different regions and revision numbers, and all the other information we need to make a movie sync.

And this system might have been fine in the past, but the days are gone where a game can exist only on one platform. Nowadays game versions on different platforms are so similar, it can make sense for one to obsolete the other. And if that's the case, an obsoletion-based design makes more sense. 

### New System
The new Entity will be the abstract idea of a game identified purely by a name. It's then split up into Game Versions, which can be on different platforms, have different types, and have all the information needed for movie sync.
This design of the Entity is based around the fact that different game versions can obsolete each other. And this is what we group together.
We align ourselves to what speedrun.com is doing and create this new grouping of games so that games of various types can be understood as the same game. We create a one-to-one correspondence between game versions in a collection and those who obsolete each other. In short:
*If game versions can obsolete each other, they are grouped together.*

### Suggested Changes
This gif shows my idea. The steps are further described below.
<img src="https://user-images.githubusercontent.com/22375320/159775436-af068126-546b-4f1f-ac8b-c623251e71da.gif" width="600">

<hr>

#### Part 1 - The current system
![TASGameRevamp-Page-1 drawio](https://user-images.githubusercontent.com/22375320/159775578-87b16538-9541-4723-a201-6a683f3d8516.png)

#### Part 2 - Make the new game grouping
![TASGameRevamp-Page-2 drawio](https://user-images.githubusercontent.com/22375320/159775760-37ea7d22-1a61-4afb-bd02-28148e4c800f.png)
Rename Game to GameVersion, and make a new Game Entity that groups together GameVersions. Technically this can be done by making a new Game for *every single* GameVersion (and later combine them), but because we already have chains, we can instead use our current obsoletion chains.
E.g. Pokemon Red, Green, Blue, Yellow GameVersions all get a single Pokemon RGBY Game.
The genre and overall game groups should already work out, otherwise we would have had a situation where different genres obsolete each other, which should never happen.

#### Part 3 - Move columns
![TASGameRevamp-Page-3 drawio](https://user-images.githubusercontent.com/22375320/159776536-2b81054f-a658-4c62-a939-2e528244d380.png)
All the columns that don't need to be differentiated are moved to the Game structure. The question we need to ask is, "If these versions can obsolete each other, do we really need different ___?".
SystemIds? Yes. Abbreviations? No.

#### Part 4 - Split GameRom into GameVersions
![TASGameRevamp-Page-4 drawio](https://user-images.githubusercontent.com/22375320/159777617-a4058035-5f9e-46a8-8e02-c3da61102b9b.png)
The concept of a ROM identifying a game doesn't work for more modern systems. So we split them up into different GameVersions. All information needed to sync would be included there.

#### Part 5 - The new system
![TASGameRevamp-Page-5 drawio](https://user-images.githubusercontent.com/22375320/159777957-fe457f7e-ebf0-443a-9058-0dda558dce79.png)

</details>
<hr>
<details>
<summary>Update 2022-04-26</summary>
While the suggestion like it's described in this post *could* work, after trying to start working on it it turned out to be an insane amount of work. I initially thought splitting up into as many small steps as possible would make it plausible. It turns out however that the biggest work is moving database columns.
*So a new approach is easier*:
For now, only move the SystemId from Games to GameRoms. This is already a big step as is, but it would only be one step and solve the biggest problems.
</details>
<hr>

**Update 2022-05-09**:
Again, the new idea is to move SystemId from Games to GameRoms. So here is what I suggest now. (Big or dangerous changes are **bold**.)
- [x] Add nullable empty SystemId column to GameRoms. #1275
- [x] Remove Md5 and Sh1 requirements from GameRoms. (We want to require at least one GameRom for each Game so they need to be generated with a query, and we don't have all the hashes yet) #1275
- [x] Generate GameRoms for each Game that doesn't have one. We can use the Game DisplayName for the GameRom Name.
- [x] **Fill every GameRom SystemId using the SystemId from the Game.**

Until here all changes were basically invisible database shuffling. All people might notice is suddenly every Game having a GameRom where it didn't previously. But here come the behavior changes.

- [x] **Remove every instance of Game SystemId usage and re-logic them with an according GameRom SystemId use.** (Biggest step. Prepare for ~50 files to need non-trivial adjusting.) #1276
- [x] Make sure the UI is created so adding a System to a GameRom is possible. #1276
- [x] Change GameRoms SystemId column to required instead of nullable.

And finally if everything works and is rewired properly we can do the final step.

- [x] **!! Drop the Game SystemId column. !!**

**Comment by vadosnaprimer** [comment]
I like all of it, but I have some questions.

> The new Entity will be the abstract idea of a game identified purely by a name.

There are games released on different platforms under different names
- [Universal Soldier](https://tasvideos.org/621G) is a Genesis port of Turrican II (Amiga)
- [Mega Turrican](https://tasvideos.org/622G) is a Genesis port of Turrican III (Amiga)

There are games that exist on the same platform under the same name, but they aren't versions of one another, they were made independently by different people.
- [Indiana Jones and the Last Crusade (Taito)](https://tasvideos.org/817G)
- [Indiana Jones and the Last Crusade (UBI Soft)](https://tasvideos.org/2362G)
From our chat, the solution to this one is actually putting what makes them different right into game title like the old side had to do it? Won't it look confusing like _versions of versions_?

**Comment by Masterjun3** [comment]
What do you mean by "look confusing"? In your examples I see nothing confusing.

**Comment by vadosnaprimer** [comment]
> What do you mean by "look confusing"? In your examples I see nothing confusing.

Okay I tried coming up with an obvious example of things looking obviously messy and couldn't.

**Comment by Masterjun3** [comment]
I updated the OP with the new more reasonable plan for this. I'm have a draft branch for the first few steps, and they will be marked as done once I create the PR and it gets merged.
I am currently working on the ~50 files that need adjustments.

**Comment by adelikat** [comment]
I checked all the boxes!
Should this ticket be closed now?

**Comment by Masterjun3** [comment]
Yes! Congratulations us!
